# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
      - run: npm install
      - run: npm run build

      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          # Private SSH key to register in the SSH agent
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
      - name: Setup known_hosts
        run: echo 'bg3.cs.wm.edu,128.239.2.102 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBM3V0+z4cZJIoSgHSQk6bJYXBRAZ0aOKprIvn/rD6CtdHozyoB1shsnFlwG+I3XeteUwScJfTp61pvgjYj22e24=' >> ~/.ssh/known_hosts
        
      - name: Sync project files
        run: rsync -avz --delete dist/ zwang34@bg3.cs.wm.edu:/home/zwang34/public_html/
